name: build-push-docker-image
on:
  workflow_dispatch:

  push:
    branches:
      - mlops_dev
      - mlops_prd
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set SHORT_SHA and LOWERCASE_REPO environment variable
      run: |
        echo "LOWERCASE_REPO=$(echo ${{ github.event.repository.name }} | tr [A-Z] [a-z])" >> $GITHUB_ENV
        echo "SHORT_COMMIT_SHA=${GITHUB_SHA:0:12}" >> $GITHUB_ENV

    - name: Create .Renviron
      env:
        FRAMEBAR_DATABAR_GITHUB_PAT: ${{ secrets.FRAMEBAR_DATABAR_GITHUB_PAT }}
      run: |
        touch ./.Renviron
        echo GITHUB_PAT="$FRAMEBAR_DATABAR_GITHUB_PAT" >> ./.Renviron

    - name: Login to ECR
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.LIGHT_DOCKER_USER }}
        password: ${{ secrets.LIGHT_DOCKER_TOKEN }}
        registry: ${{ secrets.LIGHT_DOCKER_REPOSITORY_URL }}
        ecr: false

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        push: true
        provenance: false
        context: .
        file: ./docker/Dockerfile
        secret-files: |
          "dot_Renviron=./.Renviron"
        tags: |
          ${{ secrets.LIGHT_DOCKER_REPOSITORY_URL }}/${{ env.LOWERCASE_REPO }}:${{ github.ref_name }}-sha-${{ env.SHORT_COMMIT_SHA }}
          ${{ secrets.LIGHT_DOCKER_REPOSITORY_URL }}/${{ env.LOWERCASE_REPO }}:${{ github.ref_name }}-sha-latest

    - name: Clean up on the GitHub hosted runner
      run: |
        rm ./.Renviron
